/**
 * Fixed LaTeX Preamble
 *
 * This is the predetermined LaTeX environment that all solutions must work within.
 * Solvers CANNOT modify this - they can only add content between the preamble and \end{document}.
 */

export const LATEX_PREAMBLE = `\\documentclass[11pt]{article}

% Packages
\\usepackage[utf8]{inputenc}
\\usepackage[T1]{fontenc}
\\usepackage{amsmath, amssymb, amsthm}
\\usepackage{mathtools}
\\usepackage{geometry}
\\usepackage{enumerate}
\\usepackage{enumitem}
\\usepackage{graphicx}
\\usepackage{hyperref}
\\usepackage{tikz}
\\usepackage{algorithm}
\\usepackage{algorithmic}
\\usepackage{listings}
\\usepackage{xcolor}

% Page geometry
\\geometry{margin=1in}

% Theorem environments
\\newtheorem{theorem}{Theorem}[section]
\\newtheorem{lemma}[theorem]{Lemma}
\\newtheorem{proposition}[theorem]{Proposition}
\\newtheorem{corollary}[theorem]{Corollary}
\\newtheorem{definition}[theorem]{Definition}
\\newtheorem{example}[theorem]{Example}

% Custom commands
\\newcommand{\\R}{\\mathbb{R}}
\\newcommand{\\N}{\\mathbb{N}}
\\newcommand{\\Z}{\\mathbb{Z}}
\\newcommand{\\Q}{\\mathbb{Q}}
\\newcommand{\\C}{\\mathbb{C}}
\\newcommand{\\norm}[1]{\\left\\lVert#1\\right\\rVert}
\\newcommand{\\abs}[1]{\\left|#1\\right|}
\\newcommand{\\inner}[2]{\\left\\langle#1,#2\\right\\rangle}

% Problem formatting
\\newcommand{\\problem}[1]{\\section*{Problem #1}}
\\newcommand{\\subproblem}[1]{\\subsection*{Part #1}}
\\newcommand{\\subsubproblem}[1]{\\subsubsection*{#1}}

% Solution environment
\\newenvironment{solution}{\\paragraph{Solution:}}{}

% Listings style for code
\\lstset{
  basicstyle=\\ttfamily\\small,
  keywordstyle=\\color{blue},
  commentstyle=\\color{gray},
  stringstyle=\\color{red},
  showstringspaces=false,
  breaklines=true,
  frame=single,
  numbers=left,
  numberstyle=\\tiny\\color{gray}
}

\\begin{document}

\\title{Problem Set Solutions}
\\author{Generated by Multi-Agent Solver}
\\date{\\today}
\\maketitle

\\tableofcontents
\\newpage
`;

export const LATEX_POSTAMBLE = `
\\end{document}
`;

/**
 * Create a complete LaTeX document from solution content
 */
export function createDocument(content: string): string {
  return `${LATEX_PREAMBLE}\n${content}\n${LATEX_POSTAMBLE}`;
}

/**
 * Create a test document for compilation checking
 * Used during the solver's compilation loop
 */
export function createTestDocument(solutionContent: string): string {
  return createDocument(solutionContent);
}

/**
 * Format a problem header based on its hierarchy level
 */
export function formatProblemHeader(problemNumber: string, level: number): string {
  if (level === 0) {
    return `\\problem{${problemNumber}}`;
  } else if (level === 1) {
    return `\\subproblem{${problemNumber}}`;
  } else {
    return `\\subsubproblem{${problemNumber}}`;
  }
}
